# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NumberGuess.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 232)
        MainWindow.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"background-color: rgb(0, 170, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 20, 211, 20))
        font = QtGui.QFont()
        font.setFamily("Elephant")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.TextField = QtWidgets.QLineEdit(self.centralwidget)
        self.TextField.setGeometry(QtCore.QRect(150, 60, 113, 20))
        self.TextField.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.TextField.setObjectName("TextField")
        self.Check = QtWidgets.QPushButton(self.centralwidget)
        self.Check.setGeometry(QtCore.QRect(160, 100, 51, 23))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.Check.setFont(font)
        self.Check.setStyleSheet("background-color: rgb(255, 170, 255);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.Check.setObjectName("Check")
        self.Reset = QtWidgets.QPushButton(self.centralwidget)
        self.Reset.setGeometry(QtCore.QRect(220, 100, 41, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Reset.setFont(font)
        self.Reset.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.Reset.setObjectName("Reset")
        self.OutputLabel = QtWidgets.QLabel(self.centralwidget)
        self.OutputLabel.setGeometry(QtCore.QRect(80, 160, 211, 21))
        font = QtGui.QFont()
        font.setFamily("High Tower Text")
        font.setPointSize(16)
        font.setItalic(True)
        self.OutputLabel.setFont(font)
        self.OutputLabel.setStyleSheet("color: rgb(255, 255, 127);")
        self.OutputLabel.setText("")
        self.OutputLabel.setObjectName("OutputLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Number Guessing Game"))
        self.label_2.setText(_translate("MainWindow", "Enter a Number"))
        self.Check.setText(_translate("MainWindow", "Check"))
        self.Reset.setText(_translate("MainWindow", "Reset"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
